In [5]:
import pandas as pd
import numpy as np
from datetime import date
from scipy.sparse import coo_matrix

data_df = pd.read_csv('./ratings.csv', sep=',', names=["UserID", "MovieID", "Rating", "Timestamp"],dtype={'Rating':'float64'})

#dataframe object with movie information
header_names=[
        "adult",
        "belongs_to_collection", 
        "budget",
        "genres",
        "homepage",
        "movieId",
        "imdb_id",
        "original_language",
        "original_title",
        "overview",
        "popularity",
        "poster_path",
        "production_companies",
        "production_countries",
        "release_date",
        "revenue",
        "runtime",
        "spoken_languages",
        "status",
        "tagline",
        "title",
        "video",
        "vote_average",
        "vote_count"]
movie_data_df = pd.read_csv('./movies_metadata.csv', sep=',', names= header_names)

# filtering ratings before certain time to help with memory space
data_df['Timestamp'] = pd.to_datetime(data_df['Timestamp'], unit='s')
cutoff_date = "2017-06-01" # this was the earliest i could do without a memory error
data_df = data_df[data_df['Timestamp'] >= cutoff_date]
# print("data_df after second filter")
# print(data_df.info())        
data_df.to_csv('filtered_ratings.csv', index=False)


# First, generate dictionaries for mapping old id to new id for users and movies
unique_MovieID = data_df['MovieID'].unique()
unique_UserID = data_df['UserID'].unique()
j = 0
user_old2new_id_dict = dict()
for u in unique_UserID:
    user_old2new_id_dict[u] = j
    j += 1
j = 0
movie_old2new_id_dict = dict()
for i in unique_MovieID:
    movie_old2new_id_dict[i] = j
    j += 1
    
# Then, use the generated dictionaries to reindex UserID and MovieID in the data_df
user_list = data_df['UserID'].values
movie_list = data_df['MovieID'].values
for j in range(len(data_df)):
    user_list[j] = user_old2new_id_dict[user_list[j]]
    movie_list[j] = movie_old2new_id_dict[movie_list[j]]
data_df['UserID'] = user_list
data_df['movieID'] = movie_list

# generate train_df with 70% samples and test_df with 30% samples, and there should have no overlap between them.
train_index = np.random.random(len(data_df)) <= 0.7
train_df = data_df[train_index]
test_df = data_df[~train_index]

# generate train_mat and test_mat
num_user = len(data_df['UserID'].unique())
num_movie = len(data_df['MovieID'].unique())
num_ratings = len(data_df['Rating'])
print(num_ratings)

# print(train_df.info())
train_mat = coo_matrix((train_df['Rating'].values, (train_df['UserID'].values, train_df['MovieID'].values)), shape=(num_user, num_movie)).astype(float).toarray()
test_mat = coo_matrix((test_df['Rating'].values, (test_df['UserID'].values, test_df['MovieID'].values)), shape=(num_user, num_movie)).astype(float).toarray()

data_df before first filter
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype  
---  ------     -----  
 0   UserID     int64  
 1   MovieID    int64  
 2   Rating     float64
 3   Timestamp  int64  
dtypes: float64(1), int64(3)
memory usage: 794.2 MB
None
356861


In [9]:
train_mat = (train_mat > 0).astype(float)
test_mat = (test_mat > 0).astype(float)

print(train_mat)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


user-user Collaborative Filtering with implicit feedback (from hw2) SWITCH TO ITEM-ITEM

In [10]:
#implicit user user collab filtering

# numer = np.matmul(train_mat, train_mat.T)
# denom = np.sum(train_mat ** 2, axis=1, keepdims=True) ** 0.5
# Cosine = numer / np.matmul(denom, denom.T)

# calculating cosinne similarity between items
num_rating_items = np.sum(train_mat, axis=0, keepdims=True)
numer = np.matmul(train_mat.T, train_mat)  # num_item * num_item
denom = num_rating_items.T + num_rating_items - numer  # num_item * num_item
denom[denom == 0] = 1
cosine_sim_mat = numer / denom  # num_item * num_item
print(cosine_sim_mat)

[[1.         0.13636364 0.075      ... 0.         0.         0.        ]
 [0.13636364 1.         0.11023622 ... 0.         0.         0.        ]
 [0.075      0.11023622 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [11]:
#use cosine sim mat to give recommendations

#track which items the user likes so we can find similar items
user_train_like = []
for u in range(num_user):
    user_train_like.append(np.where(train_mat[u,:] > 0)[0])

# use equation to get a predicted preference score based on similarity between items 
prediction_mat = train_mat.copy()
for i in range(num_movie):
    similarities = cosine_sim_mat[i, :]
    similarities[i] = -1
    N_idx = np.argpartition(similarities, -10)[-10:]
    N_sim = similarities[N_idx]
    prediction_mat[:, i] = np.sum(N_sim.reshape((1, -1)) * train_mat[:, N_idx], axis=1) / (np.sum(N_sim) + 1e-10)
    
print(prediction_mat[0])

recommendation = [] # will append each user's top 50 movies here
for u in range(num_user):
    train_like = user_train_like[u]
    prediction_mat[u][train_like] = -9999 # don't recommend what user already liked
    top50_iid = np.argpartition(prediction_mat[u], -50)[-50:]
    top50_iid = top50_iid[np.argsort(prediction_mat[u][top50_iid])[-1::-1]]
    recommendation.append(top50_iid)
    
print(recommendation[0]) #top 50 movies for user 0

[0.50496138 0.47812625 0.38141906 ... 0.         0.         0.        ]
[19397 13992 17711 14343   126    39    38    58    64    45   311    41
   104   249   962   178   121   330   786   351  1139  1004   132   265
   262   207    88  2063   506    67  2017   924   551   541   215   461
   593  2095   505   179    31    68   393    47   501   456   799   218
   907   790]


In [18]:
# use the prediction mat to recommend movies to the group

user_group = [750, 50, 50] # FIXME - change this to ID of whoever is in group instead of hardcode

# get the groups average predicted preference for each movie
average_ratings = []

for i in range(num_movie):
    rating_sum = 0.0
    for u in user_group:
        
        rating_sum+=prediction_mat[u][i]
    # only give them rec if the movie is in the movie_metadata file
    if i in movie_data_df["movieId"]:
        average_ratings.append(rating_sum)
    #average_ratings.append(rating_sum)

top_50 = np.argsort(average_ratings)[-50:] # ID of 50 movies with the highest total preference
print(top_50)
    

[  104   132   262   606   529   548   680   765    99   275    81   809
   187    34   546   203   330   232   240   523   222  1076    44   184
    22   250   224  2026   242    48   688   258    54   218   635   506
  1089   574   195    35   217   209   652   154    37 11077   173   386
 18273 15293]


In [17]:
# Calculate recall@k, precision@k with k=5, 20, 50 and print out the average over all users for these 6 metrics.
# Your Code Here...

user_test_like = []
for u in range(num_user):
    user_test_like.append(np.where(test_mat[u, :] > 0)[0])
    
recalls = np.zeros(3)
precisions = np.zeros(3)
user_count = 0.

for u in range(num_user):
    test_like = user_test_like[u]
    test_like_num = len(test_like)
    if test_like_num == 0:
        continue
    rec = recommendation[u]
    hits = np.zeros(3)
    for k in range(50):
        if rec[k] in test_like:
            if k < 50:
                hits[2] += 1
                if k < 20:
                    hits[1] += 1
                    if k < 5:
                        hits[0] += 1
    recalls[0] += (hits[0] / test_like_num)
    recalls[1] += (hits[1] / test_like_num)
    recalls[2] += (hits[2] / test_like_num)
    precisions[0] += (hits[0] / 5.)
    precisions[1] += (hits[1] / 20.)
    precisions[2] += (hits[2] / 50.)
    user_count += 1

recalls /= user_count
precisions /= user_count

print('recall@5\t[%.6f],\t||\t recall@20\t[%.6f],\t||\t recall@50\t[%.6f]' % (recalls[0], recalls[1], recalls[2]))
print('precision@5\t[%.6f],\t||\t precision@20\t[%.6f],\t||\t precision@50\t[%.6f]' % (precisions[0], precisions[1], precisions[2]))

recall@5	[0.073838],	||	 recall@20	[0.178107],	||	 recall@50	[0.264495]
precision@5	[0.137508],	||	 precision@20	[0.114519],	||	 precision@50	[0.085970]
